apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret  # Replace with the name of your secret
      containers:
      - name: devopshint
        image: registry.gitlab.com/arafat.sayad402/portfolio:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
