on:
    push:
      branches: [main]
  
  jobs:
    build:
      runs-on: [ubuntu-latest]
      steps:
        - name: Checkout Source
          uses: actions/checkout@v3
        - name: Create env file
          run: |
            touch .env
            echo "${{ secrets.SERVER_ENV_PROD }}" > .env
            cat .env
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker images
          run: docker build -t sayad1/arafat-protfolio-app .
        - name: Publish Images to Docker Hub
          run: docker push sayad1/arafat-protfolio-app:latest
  